postgres.port: 5432
postgres.host: localhost
postgres.database-name: otus
postgres.pass: ${postgres.password:docker}
postgres.user: ${postgres.username:docker}
postgres.url: jdbc:postgresql://${postgres.host:localhost}:${postgres.port}/${postgres.database-name}?useSSL=false

spring:
  application:
    name: otus-homework

  datasource:
    url: ${postgres.url}
    username: ${postgres.user}
    password: ${postgres.pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: 'create-drop'

server:
  port: 8000

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles[http.server.requests]: 0.5, 0.7, 0.95, 0.99
      percentiles-histogram:
        "[http.server.requests]": true
      slo[http.server.requests]: 10ms, 50ms, 100ms, 200ms, 300ms, 400ms, 500ms

