#apiVersion: networking.istio.io/v1alpha3
#kind: Sidecar
#metadata:
#  name: proxy-app
#  namespace: default
#spec:
#  egress:
#    - hosts:
#        - "default/oauth2-proxy.default.svc.cluster.local" # Разрешаем сервису ходить к oauth2
#  outboundTrafficPolicy:
#    mode: REGISTRY_ONLY
#  workloadSelector:
#    labels:
#      app: proxy-app
---
#apiVersion: networking.istio.io/v1alpha3
#kind: Sidecar
#metadata:
#  name: proxy-app
#  namespace: default
#spec:
#  egress:
#    - hosts:
#        - "default/otus-service.default.svc.cluster.local" # Разрешаем сервису ходить к otus
#  outboundTrafficPolicy:
#    mode: REGISTRY_ONLY
#  workloadSelector:
#    labels:
#      app: proxy-app
---
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: proxy-app
  namespace: default
spec:
  egress:
    - hosts:
        - "default/otus-otus-chart.default.svc.cluster.local" # Разрешаем сервису ходить к otus
  outboundTrafficPolicy:
    mode: REGISTRY_ONLY
  workloadSelector:
    labels:
      app: proxy-app
