apiVersion: v1
kind: ConfigMap
metadata:
  name: otus-config
  labels:
    app: otus
data:
  postgres.host: {{ (include "postgresql.fullname" .)}}
  postgres.port: "5432"
  postgres.database-name: "postgres"
---
apiVersion: v1
kind: Secret
metadata:
  name: otus-secret
type: Opaque
data:
  username: {{ .Values.postgresql.auth.username | b64enc | quote }}
  password: {{ .Values.postgresql.auth.postgresPassword | b64enc | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otus-chart.fullname" . }}-grafana-dashboards
  labels:
    grafana_dashboard: "1"
data:
  {{- (.Files.Glob "dashboards/*").AsConfig | nindent 1 }}

