---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-service
spec:
  hosts:
    - yandex.ru
  ports:
    - number: 80
      name: http
      protocol: http
  resolution: DNS

---
apiVersion: v1
kind: Service
metadata:
  name: external-service
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: external-service
spec:
  hosts:
    - external-service
  http:
    - match:
        - authority:
            exact: external-service
      route:
        - destination:
            host: yandex.ru
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: otus-vs-service
spec:
  hosts:
    - arch.homework
  gateways:
    - http-gateway
  http:
    - route:
        - destination:
            host: otus-service.default.svc.cluster.local
            subset: v1
          weight: 50
        - destination:
            host: otus-service.default.svc.cluster.local
            subset: v2
          weight: 50
      retries:
        attempts: 3
        retryOn: 5xx
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: otus-destination
spec:
  host: otus-service
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
