apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
        - args:
            - --provider=oidc
            - "--insecure-oidc-allow-unverified-email=true"
            - --email-domain=*
            - --upstream=file:///dev/null
            - --http-address=0.0.0.0:4180
            - --cookie-name=s
            - --pass-authorization-header=true
            - --pass-access-token=true
            - --set-xauthrequest=true
          env:
            - name: OAUTH2_PROXY_OIDC_ISSUER_URL
              value: "http://keycloak:8080/realms/otus"
            - name: OAUTH2_PROXY_CLIENT_ID
              value: otus-client
            - name: OAUTH2_PROXY_CLIENT_SECRET
              value: iKdf0SPV8U5j5SPLEoChN0IYUuHwbOXe
            - name: OAUTH2_PROXY_COOKIE_SECRET
              value: MTExMTExMTExMTExMTExMQ==
            - name: OAUTH2_PROXY_SKIP_PROVIDER_BUTTON
              value: "true"
            - name: OAUTH2_PROXY_SET_AUTHORIZATION_HEADER
              value: "true"
            - name: OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER
              value: "true"
            - name: OAUTH2_PROXY_SSL_UPSTREAM_INSECURE_SKIP_VERIFY
              value: "true"
            - name: OAUTH2_PROXY_SESSION_STORE_TYPE
              value: "cookie"
          image: quay.io/pusher/oauth2_proxy:latest
          imagePullPolicy: Always
          name: oauth2-proxy
          ports:
            - containerPort: 4180
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
spec:
  ports:
    - name: http
      port: 4180
      protocol: TCP
      targetPort: 4180
  selector:
    k8s-app: oauth2-proxy
